<?php

namespace Diem\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DmPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DmPageRepository extends EntityRepository {

  public function findOneBySlug($slug, $culture = null) {
    return $this->createQueryBuilder('p')
            ->leftJoin('p.dmPageTranslation', 'pTranslation')
            ->where('pTranslation.slug = ?1')->setParameter(1, $slug)
            ->andWhere('pTranslation.lang = ?2')->setParameter(2, $culture)
            ->getQuery()
            ->getSingleResult();
  }

}