imports:
    - { resource: parameters.ini }

framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: %csrf_secret%
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false

# Doctrine Configuration
doctrine:
    dbal:
      default_connection: default
      connections:
          default:
              driver:   %database_driver%
              host:     %database_host%
              dbname:   %database_name%
              user:     %database_user%
              password: %database_password%
              logging:  %kernel.debug%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    DiemCoreBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%


security:
    providers:
        # the naming of a security provider is up to you, we chose "fos_userbundle"
        fos_userbundle:
            id: fos_user.user_manager
    firewalls:
        main:
            pattern:      .*
            form-login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:       true
            anonymous:    true

fos_user:
    db_driver: orm
    provider_key: main
    class:
        model:
            user: Diem\CoreBundle\Entity\User
