#_welcome:
#    resource: "@AcmeDemoBundle/Controller/WelcomeController.php"
#    type:     annotation

#homepage:
#    pattern:  /
#    defaults: { _controller: FrameworkBundle:Default:index }

diem:
    resource: "@DiemFrontBundle/Resources/config/routing.yml"

